project:
  type: website

execute:
  freeze: auto

website:
  title: "Tim Cosemans"
  description: "Tim is a data scientist working at the intersection of AI, business and education."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv/index.qmd
        text: CV
      - href: blog/index.qmd
        text: Blog
  page-footer:
    left: "(c) Tim Cosemans, 2025 – [Disclaimer](disclaimer)"

format:
  html:
    theme:
      - cosmo
    toc: true
    toc_depth: 3
    toc_float: true
    toc_smooth_scroll: true
    toc_highlight: true
    fig-align: center



