project:
  type: website

website:
  title: ''
  search: true
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: projects/projects.qmd
        text: Projects
      - href: research.qmd
        text: CV
    right: 
      - href: blog.qmd
        text: Blog

  page-footer: 
    center: "Copyright 2025, Tim Cosemans"
    left: "Based on code by [Andrew Heiss](https://github.com/andrewheiss/ath-quarto)" 
    right: 
      - icon: github
        href: https://github.com/TimCosemans
      - icon: linkedin
        href: https://linkedin.com/in/timcosemans


format:
  html:
    theme: 
      - theme.scss
    grid: 
      body-width: 900px
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai



